[package]
name = "task-abstractions"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.9"
hermit-sync = "0.1.6"
mmu-abstractions = { path = "../mmu-abstractions", default-features = false }
trap-abstractions = { path = "../trap-abstractions", default-features = false }
memory-space-abstractions = { path = "../memory-space-abstractions", default-features = false }
filesystem-abstractions = { path = "../filesystem-abstractions", default-features = false }

[features]
default = ["no_std"]
std = []
no_std = []
