[package]
name = "trap-abstractions"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
downcast-rs = { version = "2.0", default-features = false }

[features]
default = ["no_std"]
std = []
no_std = []
